version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis_data:/data"

  concert_calendar:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

