#DB
spring:

  datasource:
    url: jdbc:mysql://database-1.c3kyqq0uybnu.ap-northeast-2.rds.amazonaws.com:3306/ConcertCalendar?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ENC(hye2XoRlIzvd0+3ns2bkNA==)
    password: ENC(v82oOCcw748qmEp21qCyLP20krF4HTK7)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

  redis:
    host: my_redis
    port: 6379

#  sql:
#    init:
##      schema-locations: classpath*:init-data/schema.sql
#      data-locations: classpath*:init-data/data.sql
#      mode: always
#      separator: ;;