#DB
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ConcertCalendar?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

