#DB
spring:
  datasource:
    url: jdbc:mysql://database-1.cypfnunzf3gp.ap-northeast-2.rds.amazonaws.com:3306/ConcertCalendar?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

#JPA
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#live reload ?? ???
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

# jwt.yml ?? include
  profiles:
    include: jwt

# Redis
  redis:
    host: localhost
    port: 6379

# mail
  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: tbvjqlqlqlr1@gmail.com #앱 비밀번호 발급받은 google 계정
    password: rckhfmrxqxjucgiz #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true