#DB
spring:
  datasource:
    url: jdbc:mysql://database-1.cypfnunzf3gp.ap-northeast-2.rds.amazonaws.com:3306/ConcertCalendar?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
