cloud:
  aws:
    credentials:
      access-key: AKIA2IM7IRGFG6F3HZXO
      secret-key: 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
    s3: #버킷이름
      bucket: myconcertcalendardeploy
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false
# multipartFile 용량 늘려주는 설정
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

