cloud:
  aws:
    credentials:
      access-key: ${{secrets.ACCESSKEY}}
      secret-key: ${{secrets.SECRETKEY}}
    s3: #버킷이름
      bucket: myconcertcalendardeploy
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false
# multipartFile 용량 늘려주는 설정
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

