#DB
spring:
  # application-local.yml을 사용하겠다
  profiles:
    active: local
    # jwt.yml 파일 포함
    include: jwt, aws, secret

  #JPA
  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        # show_sql은 System.out에 로그가 출력되므로 사용을 지양하자
        # show_sql: true
        # jpa에서 어떤 데이터베이스에 맞춰 쿼리를 작성할 지 표시
        dialect: org.hibernate.dialect.MySQL8Dialect

    defer-datasource-initialization: true

#    hibernate:
#      ddl-auto: update

#    h2:
#      console:
#        enabled: true
#      datasource:
#      hikari:
#        jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL

  # mail
  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: ENC(LV/KbKNiGlRlP/dmYjSz1k6kv5UzbJjTDKLvtVPRhMM=) #앱 비밀번호 발급받은 google 계정
    password: ENC(7AXqPzgLLOAzuxXtSBpFvz8zRMvF0sePIXPL/g4VClQ=) #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


# sql에 어떤 값이 바인딩 되는지 표시해주는 설정 코드
logging:
  level:
    org:
      hibernate:
        SQL: debug
#        type:
#          descriptor:
#            sql: trace
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSSz,Asia/Seoul