#DB
spring:

  datasource:
    url: jdbc:mysql://database-1.cypfnunzf3gp.ap-northeast-2.rds.amazonaws.com:3306/ConcertCalendar?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ENC(hyy60tfViPyWZOSuq1PZpg==)
    password: ENC(H0sRW63DQ+aBI+9q7b4PAZPzBTkEHSkw)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

#  sql:
#    init:
##      schema-locations: classpath*:init-data/schema.sql
#      data-locations: classpath*:init-data/data.sql
#      mode: always
#      separator: ;;