#DB
spring:
  # application-local.yml을 사용하겠다
  profiles:
    active: dev
    # jwt.yml 파일 포함
    include: jwt

  #JPA
  jpa:
    properties:
      hibernate:
        format_sql: true
        # show_sql은 System.out에 로그가 출력되므로 사용을 지양하자
        # show_sql: true
        # jpa에서 어떤 데이터베이스에 맞춰 쿼리를 작성할 지 표시
#        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: create

#    h2:
#      console:
#        enabled: true
#      datasource:
#      hikari:
#        jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL

  # Redis
  redis:
    host: localhost
    port: 6379

  # mail
  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: tbvjqlqlqlr1@gmail.com #앱 비밀번호 발급받은 google 계정
    password: rckhfmrxqxjucgiz #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


# sql에 어떤 값이 바인딩 되는지 표시해주는 설정 코드
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
server:
  ssl:
    key-store: concal-keystore.p12
    key-store-type: PKCS12
    key-store-password: jp025879
    key-alias: ConCal-keystore
